title: "Reproducible Research: Peer Assessment 1"

## Loading and preprocessing the data


unzip(zipfile="activity.zip")
actData <- read.csv("activity.csv")

## What is mean total number of steps taken per day?
library(ggplot2)
totSteps <- tapply(actData$steps, actData$date, FUN=sum, na.rm=TRUE)
qplot(totSteps, binwidth=1000, xlab="total number of steps taken per day")
mean(totSteps, na.rm=TRUE)
median(totSteps, na.rm=TRUE)

## What is the average daily activity pattern?


Make a time series plot of the 5-minute interval (x-axis) and 
the average number of steps taken, averaged across all days (y-axis)

library(ggplot2)
avgs <- aggregate(x=list(steps=actData$steps), by=list(interval=actData$interval),
                      FUN=mean, na.rm=TRUE)
ggplot(data=avgs, aes(x=interval, y=steps)) +
    geom_line() +
    xlab("5-minute interval") +
    ylab("average number of steps taken")

On average across all the days in the dataset, the 5-minute interval contains the maximum number of steps?

averages[which.max(avgs$steps),]


## Imputing missing values

missing <- is.na(actData$steps)
table(missing)

All of the missing values are filled in with mean value for that 5-minute interval.

# Replace each missing value with the mean value of its 5-minute interval
fillValue <- function(steps, interval) {
    filled <- NA
    if (!is.na(steps))
        filled <- c(steps)
    else
        filled <- (avgs[avgs$interval==interval, "steps"])
    return(filled)
}
filledData <- actData
filledData$steps <- mapply(fillValue, filledData$steps, filledData$interval)

make a histogram of the total number of steps taken each day and calculate the mean and median total number of steps.
totalSteps <- tapply(filledData$steps, filledData$date, FUN=sum)
qplot(totalSteps, binwidth=1000, xlab="total number of steps taken each day")
mean(totalSteps)
median(totalSteps)


## Are there differences in activity patterns between weekdays and weekends?

daytype <- function(date) {
    day <- weekdays(date)
    if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
        return("weekday")
    else if (day %in% c("Saturday", "Sunday"))
        return("weekend")
    else
        stop("invalid date")
}
filledData$date <- as.Date(filledData$date)
filledData$day <- sapply(filledData$date, FUN=daytype)


